### ISSUE TITLE
reprint2.py 部分函数报错

### ISSUE THREAD

**Issue by XianwuLin** [snkasi/Tools#1]
您好：

我在使用reprint2.py这个脚本的时候，发现output类中有一些函数有报错，麻烦请修复一下：
![1](https://user-images.githubusercontent.com/5524532/49777927-8326f180-fd3d-11e8-9cd1-22758577f325.jpg)

**Comment by snkasi** [comment]
哪里报错了呀 ，信息有点少   --？

**Comment by XianwuLin** [comment]
* clear函数没有self参数 [pylint] Method has no argument [E0211] 、 [pylint] Undefined variable 'self' [E0602]
* change函数和append调用了clear函数  [pylint] Too many positional arguments for method call [E1121]
* append函数的变量x找不到定义  [pylint] Undefined variable 'x' [E0602]
* remove函数的变量i找不到定义 [pylint] Undefined variable 'i' [E0602]

具体截图请见：https://user-images.githubusercontent.com/5524532/49777927-8326f180-fd3d-11e8-9cd1-22758577f325.jpg

**Comment by snkasi** [comment]
修复了
哈哈哈，之前fork了一份原作者的代码，发现有小bug，临时修复了一下，后来给作者提issue，作者官方修复了就直接把内容合并回来了，合并的时候没仔细看...
挺好奇这么严重的问题为啥以前编辑器的pylint怎么没检测出来  --！
